name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [14, 16, 18]
        operating-system: [ubuntu-latest, self-hosted]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
